Repository googleapis/java-storage, pull requests merged in 2020-08, with the labels that each got.

#447 fix: Ignore CONTRIBUTING.md
  CONTRIBUTING.md
  synth.py
Labels: automerge, cla: yes

#449 feat: expose updateTime field of the bucket
  google-cloud-storage/clirr-ignored-differences.xml
  google-cloud-storage/src/main/java/com/google/cloud/storage/Bucket.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/BucketInfoTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/BucketTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: cla: yes

#444 Add cloud-RAD for Java
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: cla: yes, context: full

#462 test: conversion easymock to mockito
  google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplMockitoTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
Labels: cla: yes

#459 chore: update common templates
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/integration.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/continuous/samples.cfg
  .kokoro/dependencies.sh
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/lint.cfg
  synth.metadata
Labels: cla: yes, context: full

#466 chore: regenerate README
  README.md
  synth.metadata
Labels: cla: yes, context: none

#473 samples: add presubmit lint check
  .github/workflows/samples.yaml
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: partial

#475 build: temporarily disable reporting to unblock releases
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: storage, cla: yes, context: full

#335 feat: add support of daysSinceNoncurrentTime and noncurrentTimeBefore OLM options
  google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/BucketInfoTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: cla: yes

#396 feat: add support of customTimeBefore and daysSinceCustomTime
  google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/BucketInfoTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: cla: yes

#413 feat: add support of customTime metadata
  google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/BlobInfoTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/BlobTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: api: storage, cla: yes

#479 fix: set IT_SERVICE_ACCOUNT_EMAIL for nightly integration test
  .kokoro/nightly/integration.cfg
Labels: api: storage, cla: yes

#484 fix: add missing Bucket and Blob FieldSelector
  google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
Labels: cla: yes

#482 build(java): switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: storage, cla: yes, context: full

#487 fix: use property for kms client version
  google-cloud-storage/pom.xml
Labels: api: storage, cla: yes

#490 docs: update link
  google-cloud-storage/clirr-ignored-differences.xml
Labels: cla: yes
