Repository googleapis/java-storage, pull requests merged in 2020-06, with the labels that each got.

#347 chore: update README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#337 chore: Suppressing Warnings
  google-cloud-storage/src/test/java/com/google/cloud/storage/BucketInfoTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/BucketTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: cla: yes, do not merge

#351 feat: stub implementation of StorageRpc for the sake of testing
  google-cloud-storage/src/main/java/com/google/cloud/storage/testing/StorageRpcTestBase.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/testing/StorageRpcTestBaseTest.java
Labels: cla: yes

#348 chore: generate CODEOWNERS from templates
  .github/CODEOWNERS
  .repo-metadata.json
  synth.metadata
Labels: automerge, cla: yes

#354 test: convert a portion of tests from easymock to mockito
  google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplMockitoTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
Labels: cla: yes

#355 chore: update common templates
  .kokoro/build.sh
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#360 chore: regenerate README versions
  README.md
Labels: automerge, cla: yes, context: none

#364 chore: update README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#340 deps: bump shared-deps version and add back certain test deps
  pom.xml
Labels: automerge, cla: yes

#352 feat: delete bucket OLM rules
  google-cloud-storage/clirr-ignored-differences.xml
  google-cloud-storage/src/main/java/com/google/cloud/storage/Bucket.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/BucketInfoTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/BucketTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: cla: yes

#374 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#379 test: fix flaky testBucketPolicyV1RequesterPays it test
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: cla: yes

#377 samples: migrate samples from GoogleCloudPlatform/java-docs-samples /storage/cloud-client
  samples/snippets/src/main/java/com/example/storage/QuickstartSample.java
  samples/snippets/src/test/java/com/example/storage/QuickstartSampleIT.java
Labels: cla: yes

#382 chore: re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#385 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#141 feat: expose all the methods of notification
  google-cloud-storage/clirr-ignored-differences.xml
  google-cloud-storage/pom.xml
  google-cloud-storage/src/main/java/com/google/cloud/storage/NotificationInfo.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpcSpans.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/testing/StorageRpcTestBase.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/NotificationInfoTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/testing/StorageRpcTestBaseTest.java
  pom.xml
Labels: cla: yes

#393 Revert "feat: expose all the methods of notification"
  google-cloud-storage/clirr-ignored-differences.xml
  google-cloud-storage/pom.xml
  google-cloud-storage/src/main/java/com/google/cloud/storage/NotificationInfo.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpcSpans.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/testing/StorageRpcTestBase.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/NotificationInfoTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/testing/StorageRpcTestBaseTest.java
  pom.xml
Labels: cla: yes

#269 feat: add storage.upload(path)
  google-cloud-storage/clirr-ignored-differences.xml
  google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteChannel.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/testing/StorageRpcTestBase.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/BlobWriteChannelTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplMockitoTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: cla: yes

#390 feat: Add support to disable logging from bucket
  google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/BucketInfoTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/BucketTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: cla: yes
