Repository googleapis/java-storage, pull requests merged in 2020-05, with the labels that each got.

#300 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#307 ci: enable GitHub actions
  .github/workflows/ci.yaml
  .kokoro/build.bat
  synth.metadata
Labels: automerge, cla: yes, context: full

#303 chore: Create CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#315 docs: update CONTRIBUTING.md to include code formatting (#534)
  CONTRIBUTING.md
  synth.metadata
Labels: cla: yes, context: full

#312 docs: catch actual exception in java doc comment
  google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
Labels: automerge, cla: yes

#308 fix: blob.reload() does not work as intuitively expected
  google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/BlobTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: cla: yes

#317 docs: update readme to point client libarary documentation
  README.md
Labels: cla: yes

#318 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#325 feat: adopt flatten-maven-plugin and java-shared-dependencies
  google-cloud-storage/pom.xml
  pom.xml
Labels: cla: yes

#324 docs(fix): update client documentation link
  .repo-metadata.json
Labels: cla: yes

#327 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#331 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#330 test: convert a portion of tests from easymock to mockito
  google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplMockitoTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
Labels: cla: yes

#311 Add doc for equals method in blob
  google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
Labels: cla: yes

#336 test: convert a portion of tests from easymock to mockito
  google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplMockitoTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
Labels: cla: yes
