Repository googleapis/java-storage, pull requests merged in 2020-07, with the labels that each got.

#416 chore: ignore backup files
  .gitignore
Labels: automerge, cla: yes

#412 chore: Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#417 dep: update dependencies
  google-cloud-storage/pom.xml
  pom.xml
Labels: cla: yes

#397 ci(java): run dependency test on Java 8 and 11
  .github/workflows/ci.yaml
  .kokoro/dependencies.sh
  synth.metadata
Labels: cla: yes, context: full

#398 fix: PostPolicyV4.PostFieldsV4.Builder.addCustomMetadataField() allows to add prefixed an not prefixed custom fields
  google-cloud-storage/src/main/java/com/google/cloud/storage/PostPolicyV4.java
Labels: cla: yes

#434 fix(docs): example of Storage#testIamPermissions
  google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
Labels: cla: yes

#338 feat: auto content-type on blob creation
  google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: cla: yes

#430 feat: add support of startOffset and endOffset
  google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: cla: yes

#387 test: ITStorageTest requires Permission 'cloudkms.keyRings.setIamPolicy'
  CONTRIBUTING.md
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: cla: yes

#438 feat: add support of null to remove the CORS configuration from bucket
  google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/BucketTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: cla: yes

#441 chore: Re-generated to pick up changes
  CONTRIBUTING.md
  README.md
  synth.metadata
Labels: cla: yes, context: none

#439 test: ITStorage cleanup
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: cla: yes
