Repository googleapis/java-storage, pull requests merged in 2020-09, with the labels that each got.

#494 docs: update libraries-bom
  README.md
Labels: cla: yes

#492 fix: prevent NPE in RemoteStorageHelper.cleanBuckets
  google-cloud-storage/src/main/java/com/google/cloud/storage/testing/RemoteStorageHelper.java
Labels: api: storage, cla: yes

#456 feat: expose timeStorageClassUpdated property of blob's
  google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/BlobInfoTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/BlobTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: api: storage, cla: yes

#504 docs: update libraries-bom
  README.md
Labels: api: storage, cla: yes

#507 fix: KMS Bad Key error when using existing Blob context to overwrite object
  google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: api: storage, cla: yes

#524 chore: ignore generation of nightly kokoro config
  synth.py
Labels: api: storage, cla: yes

#533 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: storage, cla: yes

#540 docs: update libraries-bom
  README.md
Labels: cla: yes

#541 chore: regenerate templates
  .github/CODEOWNERS
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#543 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
