Repository googleapis/java-storage, pull requests merged in 2021-06, with the labels that each got.

#846 fix: improve error detection and reporting for BlobWriteChannel retry state
  google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteChannel.java
Labels: api: storage, cla: yes

#852 fix: update BucketInfo translation code to properly handle lifecycle rules
  google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/BucketInfoTest.java
Labels: api: storage, cla: yes

#857 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, cla: yes

#861 test: remove error string matching
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: api: storage, cla: yes

#862 build(ci): remove linkage-monitor to pass 1.106.1 patch ci
  .github/sync-repo-settings.yaml
Labels: api: storage, cla: yes

#865 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#869 build: rename 1.106.1 patch branch name
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: storage, cla: yes

#871 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#872 feat: Add shouldReturnRawInputStream option to Get requests
  google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: api: storage, cla: yes

#879 fix: Update dependencies.sh to not break on mac
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full

#882 build: configure branch 1.111.3-patch as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: storage, cla: yes

#884 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#883 feat: configure initial sp version
  .github/workflows/ci.yaml
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: api: storage, cla: yes

#887 fix: patch life cycle validation fix (1.111.3 patch)
  google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
Labels: api: storage, cla: yes

#890 chore: minimize noise from build scripts
  .kokoro/coerce_logs.sh
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full

#894 fix: Add `shopt -s nullglob` to dependencies script
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full

#897 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#899 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#898 docs: add notice about broken OLM experience
  google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
Labels: api: storage, cla: yes

#888 feat: Add from and to storage url options for BlobId
  google-cloud-storage/src/main/java/com/google/cloud/storage/BlobId.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/BlobIdTest.java
Labels: api: storage, cla: yes

#636 feat: add support of public access prevention
  google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/BucketInfoTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: api: storage, cla: yes

#901 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#904 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes
