Repository googleapis/java-storage, pull requests merged in 2021-11, with the labels that each got.

#1119 test(retry): add a test which ensures expected behavior of new retry handlers
  google-cloud-storage/src/main/java/com/google/cloud/storage/DefaultStorageRetryStrategy.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/DefaultRetryHandlingBehaviorTest.java
Labels: cla: yes, api: storage

#1132 feat: update all automatic retry behavior to be idempotency aware
  google-cloud-storage/src/main/java/com/google/cloud/storage/StorageOptions.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/StorageRetryStrategy.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/BlobWriteChannelTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/PackagePrivateMethodWorkarounds.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplMockitoTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RetryTestFixture.java
Labels: cla: yes, api: storage

#1135 chore(java): remove pin on Apache Maven 3.8.1 from github actions
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: storage, automerge, context: full

#1136 Update ci.yaml
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: storage, context: full

#1140 chore: cleanup cloud RAD generation
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: cla: yes, api: storage, context: full

#1141 chore: update jre to 11 for linter
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: storage, automerge, context: full

#1143 deps: update dependency com.google.cloud:google-cloud-shared-dependencies to v0.20.2
  pom.xml
Labels: cla: yes, api: storage

#1139 docs: Add comments to GCS gRPC API proto spec to describe how naming work
  gapic-google-cloud-storage-v2/src/main/java/com/google/storage/v2/StorageClient.java
  gapic-google-cloud-storage-v2/src/main/java/com/google/storage/v2/package-info.java
  grpc-google-cloud-storage-v2/src/main/java/com/google/storage/v2/StorageGrpc.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/Bucket.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/BucketOrBuilder.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/CommonRequestParams.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/CommonRequestParamsOrBuilder.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/Object.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/ObjectOrBuilder.java
  proto-google-cloud-storage-v2/src/main/proto/google/storage/v2/storage.proto
  synth.metadata
Labels: cla: yes, api: storage, automerge, context: full

#1142 fix: update StorageOptions to not overwrite any previously set host
  google-cloud-storage/src/main/java/com/google/cloud/storage/StorageOptions.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/StorageOptionsTest.java
Labels: cla: yes, api: storage

#1157 chore: remove enable-samples profile
  .kokoro/build.sh
  synth.metadata
Labels: cla: yes, api: storage, context: full, samples
