Repository googleapis/java-storage, pull requests merged in 2021-01, with the labels that each got.

#673 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#674 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#677 fix: last chunk is retriable
  google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteChannel.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/BlobWriteChannelTest.java
Labels: api: storage, automerge, cla: yes

#679 fix: unnecessary options in resumable upload URL
  google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
Labels: api: storage, cla: yes

#682 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#688 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#689 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#692 chore: adding docfx doclet resource
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full

#695 build: migrate to flakybot
  .kokoro/build.sh
Labels: api: storage, automerge, cla: yes
