Repository googleapis/java-storage, pull requests merged in 2021-05, with the labels that each got.

#806 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: storage, cla: yes, context: none

#810 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: storage, cla: yes, context: full

#808 build: configure branch sp-release as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: storage, cla: yes

#812 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#814 build: rename sp-release to 1.113.14-sp
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: storage, cla: yes

#813 feat: update ci config for 1.113.14-sp branch
  .github/workflows/ci.yaml
Labels: api: storage, cla: yes

#824 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#827 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full

#828 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#829 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#832 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#833 build: update google-api-client to use version from google-cloud-shared-dependencies
  google-cloud-storage/pom.xml
Labels: api: storage, automerge, cla: yes

#835 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full

#837 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full

#844 build: Add OLM fix branch to release please config
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: storage, cla: yes

#848 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#840 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full

#854 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes
