Repository googleapis/java-storage, pull requests merged in 2021-08, with the labels that each got.

#940 chore: fix checker-qual dependency issue
  pom.xml
Labels: api: storage, automerge, cla: yes

#933 chore: remove java 7 units check
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: storage, automerge, context: full

#944 chore: remove java7 units check from required checks in master
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: storage, automerge

#952 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: storage, automerge

#953 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: storage, automerge

#946 fix: incorrectly labeled span list(String,Map)
  google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpcSpans.java
Labels: cla: yes, api: storage

#958 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: storage, automerge

#959 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: storage, automerge

#960 feat: generate storage v2 gapic client
  gapic-google-cloud-storage-v2/src/main/java/com/google/storage/v2/StorageClient.java
  gapic-google-cloud-storage-v2/src/main/java/com/google/storage/v2/StorageSettings.java
  gapic-google-cloud-storage-v2/src/main/java/com/google/storage/v2/package-info.java
  gapic-google-cloud-storage-v2/src/main/java/com/google/storage/v2/stub/GrpcStorageCallableFactory.java
  gapic-google-cloud-storage-v2/src/main/java/com/google/storage/v2/stub/GrpcStorageStub.java
  gapic-google-cloud-storage-v2/src/main/java/com/google/storage/v2/stub/StorageStub.java
  gapic-google-cloud-storage-v2/src/main/java/com/google/storage/v2/stub/StorageStubSettings.java
  gapic-google-cloud-storage-v2/src/main/resources/com/google/storage/v2/gapic_metadata.json
  gapic-google-cloud-storage-v2/src/test/java/com/google/storage/v2/MockStorage.java
  gapic-google-cloud-storage-v2/src/test/java/com/google/storage/v2/MockStorageImpl.java
  gapic-google-cloud-storage-v2/src/test/java/com/google/storage/v2/StorageClientTest.java
  grpc-google-cloud-storage-v2/src/main/java/com/google/storage/v2/StorageGrpc.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/Bucket.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/BucketAccessControl.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/BucketAccessControlOrBuilder.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/BucketOrBuilder.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/ChecksummedData.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/ChecksummedDataOrBuilder.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/CommonObjectRequestParams.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/CommonObjectRequestParamsOrBuilder.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/CommonRequestParams.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/CommonRequestParamsOrBuilder.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/ContentRange.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/ContentRangeOrBuilder.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/Object.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/ObjectAccessControl.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/ObjectAccessControlOrBuilder.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/ObjectChecksums.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/ObjectChecksumsOrBuilder.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/ObjectOrBuilder.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/Owner.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/OwnerOrBuilder.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/PredefinedObjectAcl.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/ProjectTeam.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/ProjectTeamOrBuilder.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/QueryWriteStatusRequest.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/QueryWriteStatusRequestOrBuilder.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/QueryWriteStatusResponse.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/QueryWriteStatusResponseOrBuilder.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/ReadObjectRequest.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/ReadObjectRequestOrBuilder.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/ReadObjectResponse.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/ReadObjectResponseOrBuilder.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/ServiceConstants.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/ServiceConstantsOrBuilder.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/StartResumableWriteRequest.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/StartResumableWriteRequestOrBuilder.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/StartResumableWriteResponse.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/StartResumableWriteResponseOrBuilder.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/StorageProto.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/WriteObjectRequest.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/WriteObjectRequestOrBuilder.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/WriteObjectResponse.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/WriteObjectResponseOrBuilder.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/WriteObjectSpec.java
  proto-google-cloud-storage-v2/src/main/java/com/google/storage/v2/WriteObjectSpecOrBuilder.java
  proto-google-cloud-storage-v2/src/main/proto/google/storage/v2/storage.proto
  synth.metadata
Labels: cla: yes, api: storage, context: none

#964 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/build.sh
  .kokoro/nightly/samples.cfg
  synth.metadata
Labels: cla: yes, api: storage, automerge, context: full

#966 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: storage, automerge

#967 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: storage, automerge

#970 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: storage, automerge

#974 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: storage, automerge

#924 feat: fix post policy escape bug, update conformance tests
  google-cloud-storage/src/main/java/com/google/cloud/storage/PostPolicyV4.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/V4PostPolicyTest.java
  pom.xml
Labels: cla: yes, api: storage

#978 ci: removing linkage-monitor from the required checks
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: storage, automerge

#990 build(java): update renovate config to mark conformance tests as a test commit type
  renovate.json
  synth.metadata
Labels: cla: yes, api: storage, automerge, context: full

#992 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: storage, automerge
