Repository googleapis/java-storage, pull requests merged in 2021-07, with the labels that each got.

#909 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#912 chore: remove distributionManagement section
  pom.xml
Labels: api: storage, automerge, cla: yes

#917 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#916 chore: remove All rights reserved clause from java.header
  java.header
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full

#915 feat: fix signed url mismatch in BlobWriteChannel
  google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: api: storage, cla: yes

#918 fix: correct lastChunk retry logic in BlobWriteChannel
  google-cloud-storage/clirr-ignored-differences.xml
  google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteChannel.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/testing/StorageRpcTestBase.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/BlobWriteChannelTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: api: storage, cla: yes

#921 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#923 chore: add dependencyDashboardLabels to renovate.json
  renovate.json
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full

#930 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#935 build: configure branch java7 as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: storage, automerge, cla: yes

#937 feat: configure initial sp version
  .github/workflows/ci.yaml
Labels: api: storage, automerge, cla: yes
