Repository googleapis/java-storage, pull requests merged in 2021-12, with the labels that each got.

#1169 fix(java): add -ntp flag to native image testing command
  .kokoro/build.sh
  synth.metadata
Labels: api: storage, context: full

#1172 chore: make owlbot check required
  .github/sync-repo-settings.yaml
Labels: do not merge, api: storage

#1155 fix: update retry handling to retry idempotent requests that encounter unexpected EOF while parsing json responses
  google-cloud-storage/pom.xml
  google-cloud-storage/src/main/java/com/google/cloud/storage/DefaultStorageRetryStrategy.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/DataGeneration.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/DefaultRetryHandlingBehaviorTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/PackagePrivateMethodWorkarounds.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/CleanupStrategy.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RetryTestFixture.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/TestBench.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobWriteChannelTest.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: cla: yes, api: storage

#1176 chore: regenerate README
  README.md
Labels: api: storage

#1181 test: update TestBench to await shutdown before yielding for the next test
  google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/TestBench.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobWriteChannelTest.java
Labels: api: storage

#1182 chore: add enumeration type of library
  .repo-metadata.json
Labels: api: storage, automerge
