Repository googleapis/java-storage, pull requests merged in 2021-03, with the labels that each got.

#736 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#739 chore: remove docLava v2 doc generation
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full

#741 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#743 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#744 chore: copy README to docfx-yml dir
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full

#746 fix: npe in createFrom
  google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteChannel.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/BlobWriteChannelTest.java
Labels: api: storage, cla: yes

#752 build(java): update autorelease title check in response to the new multi release branch changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full

#759 fix(test): update blob paths used in storage.it.ITStorageTest#testDownloadPublicBlobWithoutAuthentication
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: api: storage, cla: yes

#756 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#762 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#764 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#765 chore(java): detect sample-secrets in build.sh
  .kokoro/build.sh
  synth.metadata
Labels: api: storage, automerge, build.sh, cla: yes, context: full, in, sample-secrets, samples

#766 chore: remove staging bucket v2
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full
