Repository googleapis/java-storage, pull requests merged in 2024-07, with the labels that each got.

#2610 chore: remove OwlBot required status check from sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: api: storage, size: xs

#2611 chore: correct path to script in hermetic_library_generation.yaml
  .github/workflows/hermetic_library_generation.yaml
Labels: api: storage, size: xs

#2609 chore: update renovate config to apply grouping to recently added dependencies
  renovate.json
Labels: api: storage, owlbot:ignore, size: s

#2618 chore: surround string with special characters with quotes in generation_config
  generation_config.yaml
Labels: api: storage, size: xs

#2620 chore: update owlbot yaml to match generated folder structure
  .github/.OwlBot-hermetic.yaml
Labels: api: storage, size: xs

#2622 chore: skip hermetic generation on fork PRs
  .github/workflows/hermetic_library_generation.yaml
Labels: api: storage, size: xs

#2624 chore: Add release-please to trusted contributors
  .github/trusted-contribution.yml
Labels: api: storage, size: xs

#2627 chore: disable the Owl Bot post-processor
  .github/.OwlBot.lock.yaml
Labels: api: storage, size: s

#2630 fix: update TransferManager downloads to reduce in memory buffering
  google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/ChunkedDownloadCallable.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/DirectDownloadCallable.java
Labels: api: storage, owlbot:ignore, size: s

#2625 chore: update hermetic_library_generation.yaml to only run on PRs that modify generation_config.yaml
  .github/workflows/hermetic_library_generation.yaml
Labels: api: storage, owlbot:ignore, size: xs

#2633 fix: use fast calculation for totalRemaining number of bytes from multiple ByteBuffers
  google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedReadableByteChannel.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/RewindableContent.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/ThroughputSink.java
Labels: api: storage, owlbot:ignore, size: s

#2635 fix: update Storage#readAllBytes to respect shouldReturnRawInputStream option
  google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITGzipTest.java
Labels: api: storage, owlbot:ignore, size: m

#2644 fix: update grpc resumable upload error categorization to be more tolerant
  google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedFinalizeOnCloseResumableWritableByteChannel.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/ResumableSessionFailureScenario.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/Utils.java
Labels: api: storage, owlbot:ignore, size: s

#2645 test: Turn DirectPath quickstart test back on and fix abandoned storage instance in GRPC test
  google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITGrpcTest.java
  samples/snippets/src/test/java/com/example/storage/QuickstartSampleIT.java
Labels: api: storage, size: s

#2590 feat: enable open telemetry metrics for GRPC
  google-cloud-storage/pom.xml
  google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageOptions.java
  google-cloud-storage/src/main/java/com/google/cloud/storage/OpenTelemetryBootstrappingUtils.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/ITGrpcMetricsTest.java
  pom.xml
  renovate.json
Labels: api: storage, owlbot:ignore, size: l

#2654 chore: temporarily disabled the required status on unmanaged_dependency_check
  .github/sync-repo-settings.yaml
Labels: owlbot:ignore

#2651 fix: add UnknownHostException to set of retriable IOExceptions
  google-cloud-storage/src/main/java/com/google/cloud/storage/DefaultStorageRetryStrategy.java
  google-cloud-storage/src/test/java/com/google/cloud/storage/DefaultRetryHandlingBehaviorTest.java
Labels: api: storage, owlbot:ignore, size: s
